language: haskell

# we need to do this explicitly because hspec depends on hspec-expectations...
install:
    - cabal install hspec markdown-unlit silently
    - cabal configure --enable-tests && cabal build
